# Generated by Django 4.2.5 on 2023-09-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
