# Generated by Django 4.2.5 on 2023-09-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_dummy_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dummy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
